### ISSUE TITLE
display disconnect after bootloader

### ISSUE THREAD

**Issue by mskoenz** [NVIDIA/edk2-nvidia#112]
Dear edk2-nvidia team

First off, thx for the great package!

We have encountered the follwoing issue:

We start with a completely new Jetson Orin Nano Devkit, with an nvme drive, flashed with the Nvidia SDKmanager with JetPack 6.1, and then boot it:

1) First we see the bootloader screen with the nvidia logo
2) Then the extlinux sequence with the terminal output of the linux startup
3) Lastly we land at the login screen

In order to change the logo, we followed the instructions here (https://github.com/NVIDIA/edk2-nvidia/wiki/Build-with-docker), and are using revision `r36.4.0-updates`.

We can successfully build the new uefi_jetson_RELEASE.bin, and copy it over to the according location in the nvidia dir before flashing the QSPI only:

`sudo ./flash.sh --no-systemimg -c bootloader/generic/cfg/flash_t234_qspi.xml jetson-orin-nano-devkit-nvme internal`

If we now boot the device, we see the following:

1) First the bootloader screen with our custom logo
2) Then the videofeed disconnects, i.e. the monitor says no input
3) The videofeed reconnects and we see the login screen

The time at step 2 is about the same, and the config in /boot/extlinux/extlinux.conf did not change, and was never modified:

```
TIMEOUT 30
DEFAULT primary

MENU TITLE L4T boot options

LABEL primary
      MENU LABEL primary kernel
      LINUX /boot/Image
      INITRD /boot/initrd
      APPEND ${cbootargs} root=PARTUUID=... rw rootwait rootfstype=ext4 mminit_loglevel=4 console=ttyTCU0,115200 firmware_class.path=/etc/firmware fbcon=map:0 nospectre_bhb video=efifb:off console=tty0 nv-auto-config
```

Is there a configuration we missed to not loose the videofeed?

Thank you and have a nice day!

**Comment by bobekjan** [comment]
Hi @mskoenz,

Thank you for the detailed report!

From your description it sounds like the SOC display hand-off is disabled in your custom UEFI build. You can verify this by booting with the custom UEFI flashed, pressing ESC when the logo shows to enter the UEFI Setup and navigating to Device Manager > NVIDIA Configuration > Boot Configuration. You will see that `SOC Display Hand-Off Mode` at the bottom is likely set to `Never`, you can change this to `Auto` and reboot to see if the desired behavior is restored.

You can also change the default for this option during the UEFI build by running
```
edk2_docker edk2-nvidia/Platform/NVIDIA/Jetson/build.sh --menuconfig
```
A build configuration menu should appear. Navigate to Boot Options and set the desired default value for SOC Display Hand-Off Mode.

Hope this helps.

**Comment by mskoenz** [comment]
Thank you, much appreciated, that was exactly it!

**Comment by mskoenz** [comment]
Only one follow up input: For me it was a little surprising that this is the default, as I expected the compiled bin to be identical to the one the sdkmanager sets up, but you likely have good reasons for it. Also here the same issue on the nvidia forum:

https://forums.developer.nvidia.com/t/bootloader-from-edk2-nvidia-disconnects-screen-during-extlinux-sequence/315409/7
