### ISSUE TITLE
Can't enter UEFI/ BIOS menu with keyboard at boot up

### ISSUE THREAD

**Issue by wakoko79** [NVIDIA/edk2-nvidia#31]
I was trying to enter BIOS menu but the keyboard is not working at boot up.
ESC, F11 and ENTER buttons are not working.

Specs:
Jetson Xavier NX with SEEED A206 carrier board
Jetpack 5.1 (L4T 35.2.1)

Keyboard works up to edk2-nvidia-r35.1-updates-20220930 [6bc2699](https://github.com/NVIDIA/edk2-nvidia/commit/6bc269911374499329de9795c64ac9b5eca64fd5).
Keyboard is not working starting edk2-nvidia-202209.0 [a87aded](https://github.com/NVIDIA/edk2-nvidia/commit/a87aded9d0814f6aadd1c8b6ce50481dd911fa3c).

Tested by flasing uefi_jetson.bin in tarball from [releases](https://github.com/NVIDIA/edk2-nvidia/releases).

**Comment by jbrasen** [comment]
Root cause of this issue has been indentified and we are working on a fix for it
