### ISSUE TITLE
4K display support for Orin

### ISSUE THREAD

**Issue by bobekjan** [NVIDIA/edk2-nvidia#4]
[Jetson Linux 34.1](https://developer.nvidia.com/embedded/jetson-linux-r341) suffers from an issue where booting Orin with a 4K display attached results in a framebuffer overrun and a boot failure. This has been tracked as known bootloader issue 3581719.

Pull request #3 corrects the framebuffer size computation, fixing this issue.

**Comment by jbrasen** [comment]
Fixed in rel-35
