### ISSUE TITLE
Remove BootLogo for Boottime optimization

### ISSUE THREAD

**Issue by fadhelh-nd** [NVIDIA/edk2-nvidia#92]
Hi,
We are working on Nvidia Orin platform.
We observed the a longer boot time and need to optimize it.

Please show us how to disable BootLogo,

UEFI branch: R35.4.1

Regards

**Comment by ashishsingha** [comment]
Hello @fadhelh-nd 

I think it would be better if you raise this as a question with Nvidia developer forums so that it can be tracked in a better way and other users of Nvidia UEFI can also benefit from the forum post.

Thank You.
