### ISSUE TITLE
 capsule update single image name limitation

### ISSUE THREAD

**Issue by coffinmatician** [NVIDIA/edk2-nvidia#96]
As I was reading through the code I noticed that https://github.com/NVIDIA/edk2-nvidia/blob/0c326dcc1fbee072cb03509e42fb48f0cb0c4ce2/Silicon/NVIDIA/Library/FmpDeviceLib/TegraFmp.c#L1127 probably was meant to be:

```c
  FwPackageCopyImageName (PkgName, PkgImageInfo, sizeof (PkgName));
```

instead of the current:

```c
  FwPackageCopyImageName (PkgName, PkgImageInfo, FW_IMAGE_NAME_LENGTH);
```

as the length is in terms of bytes, and not `CHAR16`s from my reading of the function's description, and other usages of it in this file.

**Comment by bobm21** [comment]
Thanks for reporting this!  Yes, it will be corrected as you indicate in an upcoming release.  Without the fix, the length of the partition name for a single image capsule update is limited to 18 CHAR16s instead of the full 36 CHAR16s that should be supported.

**Comment by bobm21** [comment]
fixed here: https://github.com/NVIDIA/edk2-nvidia/commit/99f3180994c61b476cdd0152653335a4409b810a
